# Generated by Django 5.2.3 on 2025-06-15 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название специальности"
                    ),
                ),
            ],
            options={
                "verbose_name": "Специальность",
                "verbose_name_plural": "Специальности",
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Университет",
                "verbose_name_plural": "Университеты",
            },
        ),
        migrations.CreateModel(
            name="SpecialityVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Год поступления")),
                ("cost", models.PositiveIntegerField(verbose_name="Стоимость")),
                ("deadline", models.DateField(verbose_name="Дедлайн")),
                (
                    "semesters_count",
                    models.PositiveIntegerField(verbose_name="Количество семестров"),
                ),
                (
                    "education_form_type",
                    models.CharField(
                        choices=[("очная", "Очная"), ("заочная", "Заочная")],
                        max_length=20,
                        verbose_name="Форма обучения",
                    ),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="universities.speciality",
                        verbose_name="Специальность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия специальности",
                "verbose_name_plural": "Версии специальностей",
                "unique_together": {("speciality", "year")},
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Номер семестра")),
                ("cost", models.PositiveIntegerField(verbose_name="Стоимость")),
                ("deadline", models.DateField(verbose_name="Дедлайн")),
                (
                    "speciality_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="universities.specialityversion",
                        verbose_name="Версия специальности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Семестр",
                "verbose_name_plural": "Семестры",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название предмета"),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="universities.semester",
                        verbose_name="Семестр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
            },
        ),
        migrations.AddField(
            model_name="speciality",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialties",
                to="universities.university",
                verbose_name="Университет",
            ),
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Заголовок работы"),
                ),
                ("cost", models.PositiveIntegerField(verbose_name="Стоимость")),
                ("deadline", models.DateField(verbose_name="Дедлайн")),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("эссе", "Эссе"),
                            ("контрольная", "Контрольная работа"),
                            ("реферат", "Реферат"),
                            ("курсовая", "Курсовая работа"),
                            ("курсовой проект", "Курсовой проект"),
                            ("ВКР", "Выпускная квалификационная работа"),
                        ],
                        max_length=30,
                        verbose_name="Тип работы",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="universities.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работа",
                "verbose_name_plural": "Работы",
            },
        ),
    ]
