# Generated by Django 5.2.3 on 2025-06-15 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("universities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semester",
            name="speciality",
        ),
        migrations.RemoveField(
            model_name="speciality",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="speciality",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="speciality",
            name="education_form_type",
        ),
        migrations.RemoveField(
            model_name="speciality",
            name="semesters_count",
        ),
        migrations.CreateModel(
            name="SpecialityVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Год поступления")),
                ("cost", models.PositiveIntegerField(verbose_name="Стоимость")),
                ("deadline", models.DateField(verbose_name="Дедлайн")),
                (
                    "semesters_count",
                    models.PositiveIntegerField(verbose_name="Количество семестров"),
                ),
                (
                    "education_form_type",
                    models.CharField(
                        choices=[("очная", "Очная"), ("заочная", "Заочная")],
                        max_length=20,
                        verbose_name="Форма обучения",
                    ),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="universities.speciality",
                        verbose_name="Специальность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия специальности",
                "verbose_name_plural": "Версии специальностей",
                "unique_together": {("speciality", "year")},
            },
        ),
        migrations.AddField(
            model_name="semester",
            name="speciality_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesters",
                to="universities.specialityversion",
                verbose_name="Версия специальности",
            ),
        ),
    ]
