# Generated by Django 5.2.3 on 2025-06-15 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "universities",
            "0002_remove_semester_speciality_remove_speciality_cost_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="speciality_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesters",
                to="universities.specialityversion",
                verbose_name="Версия специальности",
            ),
        ),
    ]
